apiVersion: apps/v1
kind: Deployment
metadata:
  name: "namui-wiki"
  labels:
    app: "namui-wiki"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "namui-wiki"
  template:
    metadata:
      name: "namui-wiki"
      labels:
        app: "namui-wiki"
    spec:
      containers:
        - name: "namui-wiki"
          image: "ghcr.io/rlacksgus97/namui-wiki:7900533613"
          volumeMounts:
            - name: application-properties
              mountPath: /config
              readOnly: true
      volumes:
        - name: application-properties
          configMap:
            name: namui-wiki-configmap
            items:
              - key: "application.yaml"
                path: "application.yaml"
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always