apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stg-namui-wiki
  name: stg-namui-wiki
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stg-namui-wiki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stg-namui-wiki
      name: stg-namui-wiki
    spec:
      containers:
        - image: ghcr.io/rlacksgus97/stg-namui-wiki:latest
          imagePullPolicy: Always
          name: stg-namui-wiki
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: application-properties
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application.yaml
                path: application.yaml
            name: namui-wiki-stg-configmap
          name: application-properties
